source 'https://github.com/CocoaPods/Specs.git'
source 'git@git.coding.net:CoderST/STFMSpecs.git'

platform :ios, '8.1'

target 'XDExerciseExample' do
  use_frameworks!

pod 'Alamofire'
pod 'NetWorkLib'
#pod 'SnapKit'
pod 'SVProgressHUD'
pod 'Kingfisher'
#pod 'MJExtension'
pod 'MJRefresh'
pod 'XHLaunchAd'
#pod 'SKPhotoBrowser'
#pod 'DACircularProgress', '~> 2.3.1'
#pod 'HandyJSON', '~> 1.7.2'
#pod 'RealmSwift'
pod 'YYModel'
#DKNightVersion 暂时没用，准备加入换肤功能
#GYDataCenter：高性能数据库框架(GYDataCenter 是一个 SQLite 数据库框架)
end
