source 'https://github.com/CocoaPods/Specs.git'
source 'git@git.coding.net:CoderST/STFMSpecs.git'

platform :ios, '8.1'

target 'XDExerciseExample' do
  use_frameworks!

pod 'Alamofire'

# AFNetworking3.x与YYCache的二次封装
#pod 'PPNetworkHelper'

#pod 'NetWorkLib'

pod 'ReachabilitySwift'

pod 'SDCycleScrollView'

#pod 'SnapKit'

pod 'SVProgressHUD'

pod 'Kingfisher'

#pod 'Kingfisher', '~> 3.13.1'
#pod 'MJExtension'

pod 'MJRefresh'

pod 'XHLaunchAd'

#pod 'SKPhotoBrowser'
#pod 'DACircularProgress', '~> 2.3.1'

pod 'HandyJSON', '~> 4.0.0-beta.1'

pod 'SSKeychain', '~> 1.4.1'

pod 'STRowLayout', '~> 1.0.1'
# 导航栏的平滑显示和隐藏 https://github.com/forkingdog/FDFullscreenPopGesture
pod 'FDFullscreenPopGesture'

# 轮播图 https://github.com/gsdios/SDCycleScrollView
pod 'SDCycleScrollView'

#pod 'WebViewJavascriptBridge', '~> 5.0'
#pod 'RealmSwift'
#DKNightVersion 暂时没用，准备加入换肤功能
#GYDataCenter：高性能数据库框架(GYDataCenter 是一个 SQLite 数据库框架)
#pod 'YYKit'                             , '1.0.9'
# YYKit 的一套分类

pod 'YYCategories'                      , '1.0.4'

# 富文本
pod 'YYText'                            , '1.0.7'
# 字典转模型
#pod 'YYModel'                           , '1.0.4'

# YYImage
pod 'YYImage'                           , '1.0.4'

# webP
#pod 'YYImage/WebP'

# 高性能的 iOS 缓存框架
pod 'YYCache'                    

# 高性能的 iOS 异步图像加载框架。
#pod 'YYWebImage'                        , '1.0.5'

# iOS 键盘监听管理工具
pod 'YYKeyboardManager'                 , '1.0.1'

# iOS 全局并发队列管理工具
pod 'YYDispatchQueuePool'               , '1.0'

# iOS 异步绘制与显示的工具
pod 'YYAsyncLayer'                      , '1.0'

pod 'Qiniu'

pod 'GPUImage'

# 腾讯崩溃sdk
#pod 'Bugly'

pod 'Fabric'
#pod 'Crashlytics', '~> 3.9.0'

#获取硬件信息
#Swift 4加载下面 (当前是4)
pod 'DeviceKit', '~> 1.3'
#Swift 3加载下面
#pod 'DeviceKit', '~> 1.2.3'

pod 'ZFPlayer'
end



